// Offline-first presentation runtime. Mirrors the backend state model for demos without a network/server.
const SEED_TRAINS = [
  {train_no:"13147",name:"Uttar Banga Exp",origin:"SDAH",destination:"BP",direction:"UP",current_km:1.2,speed_kmh:65,delay_minutes:0,status:"On Time",track:"UP_LINE",route_id:"CORR_SDAH_BP",priority_class:"FREIGHT"},
  {train_no:"12311",name:"Howrah Kalka UP",origin:"SDAH",destination:"BP",direction:"UP",current_km:4.8,speed_kmh:75,delay_minutes:8,status:"Caution",track:"UP_LINE",route_id:"CORR_SDAH_BP",priority_class:"FREIGHT"},
  {train_no:"31213",name:"Kalyani Local",origin:"SDAH",destination:"BP",direction:"UP",current_km:9.2,speed_kmh:45,delay_minutes:1,status:"Delayed 1m",track:"UP_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"12377",name:"Padatik Exp",origin:"SDAH",destination:"BP",direction:"UP",current_km:13.8,speed_kmh:85,delay_minutes:0,status:"On Time",track:"UP_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"22301",name:"Vande Bharat Express",origin:"SDAH",destination:"BP",direction:"UP",current_km:21.8,speed_kmh:90,delay_minutes:0,status:"On Time",track:"UP_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"13148",name:"Uttarbanga Exp DN",origin:"BP",destination:"SDAH",direction:"DN",current_km:2.2,speed_kmh:70,delay_minutes:4,status:"Caution",track:"DN_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"12312",name:"Kalka Mail DN",origin:"BP",destination:"SDAH",direction:"DN",current_km:4.6,speed_kmh:80,delay_minutes:0,status:"On Time",track:"DN_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"31212",name:"BP-SDAH Local",origin:"BP",destination:"SDAH",direction:"DN",current_km:8.9,speed_kmh:55,delay_minutes:0,status:"Caution",track:"DN_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"},
  {train_no:"12378",name:"Padatik Exp DN",origin:"BP",destination:"SDAH",direction:"DN",current_km:9.8,speed_kmh:80,delay_minutes:3,status:"Delayed 3m",track:"DN_LINE",route_id:"CORR_SDAH_BP",priority_class:"FREIGHT"},
  {train_no:"22302",name:"Vande Bharat DN",origin:"BP",destination:"SDAH",direction:"DN",current_km:18.8,speed_kmh:90,delay_minutes:0,status:"On Time",track:"DN_LINE",route_id:"CORR_SDAH_BP",priority_class:"PASSENGER"}
];
const SEED_BLOCKS = [
  {block_id:"B-106",section:"KM 6.0 - 6.8",location_from_km:6.0,location_to_km:6.8,target_track:"DN_LINE",start_time:"00:00",end_time:"23:59",duration_minutes:60,status:"Active",approved:true,disruption_type:"Track Inspection · ACTIVE SIMULATION",emergency:false,bundled_departments:["Engineering (Track)"],bundled_tasks:["ENG-1041"],train_impact_delay_minutes:6},
  {block_id:"B-108",section:"KM 16.5 - 17.2",location_from_km:16.5,location_to_km:17.2,target_track:"UP_LINE",start_time:"00:00",end_time:"23:59",duration_minutes:60,status:"Active",approved:true,disruption_type:"Signal / Point Maintenance · ACTIVE SIMULATION",emergency:false,bundled_departments:["S&T (Signalling)"],bundled_tasks:["ENG-1046"],train_impact_delay_minutes:8}
];
const STATIONS = [
  {id:"S-1",code:"S1",name:"S-1",km:0,map:{up_x:30,dn_x:30}},{id:"S-2",code:"S2",name:"S-2",km:2.5,map:{up_x:180,dn_x:180}},
  {id:"S-3",code:"S3",name:"S-3",km:5,map:{up_x:360,dn_x:360}},{id:"S-4",code:"S4",name:"S-4",km:7.5,map:{up_x:520,dn_x:520}},
  {id:"S-5",code:"S5",name:"S-5",km:10,map:{up_x:650,dn_x:650}},{id:"S-6",code:"S6",name:"S-6",km:12.5,map:{up_x:820,dn_x:820}},
  {id:"S-7",code:"S7",name:"S-7",km:15,map:{up_x:1000,dn_x:1000}},{id:"S-8",code:"S8",name:"S-8",km:17.5,map:{up_x:1120,dn_x:1120}},
  {id:"S-9",code:"S9",name:"S-9",km:20,map:{up_x:1240,dn_x:1240}},{id:"S-10",code:"S10",name:"S-10",km:22.5,map:{up_x:1320,dn_x:1320}},{id:"S-11",code:"S11",name:"S-11",km:25,map:{up_x:1405,dn_x:1405}}
];
const LOOPS = [
  {id:"LOOP-1",station:"S-4",capacity:1,exit_km:5.2,map_y_up:156,map_y_dn:156},
  {id:"LOOP-2",station:"S-7",capacity:1,exit_km:18.0,map_y_up:245,map_y_dn:245}
];

export class PresentationRuntime {
  constructor(onSnapshot){this.onSnapshot=onSnapshot;this.trains=structuredClone(SEED_TRAINS);this.blocks=structuredClone(SEED_BLOCKS);this.trains.find(t=>t.train_no==='12377').current_km=16.5;this.trains.find(t=>t.train_no==='12377').route_control={mode:'LOOP',status:'ON_LOOP',via:{loop_id:'LOOP-2',station_id:'S-7',station_code:'S7',entry_km:15,exit_km:18,block_entry_km:16.5,distance_km:2.3,capacity:1,map_y_up:245,map_y_dn:245},protected_block_id:'B-108',loop_progress_km:1.5};this.trains.find(t=>t.train_no==='12378').current_km=6.35;this.trains.find(t=>t.train_no==='12378').route_control={mode:'LOOP',status:'ON_LOOP',via:{loop_id:'LOOP-1',station_id:'S-4',station_code:'S4',entry_km:7.5,exit_km:5.2,block_entry_km:6.8,distance_km:2.3,capacity:1,map_y_up:156,map_y_dn:156},protected_block_id:'B-106',loop_progress_km:1.15};this.sequence=0;this.timer=null;this.events=[];this.ai1={};this.ai3State={};}
  start(){if(this.timer)return;this.emit();this.timer=setInterval(()=>this.tick(),900);}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  stationContext(t){const km=Number(t.current_km);if(t.direction==='UP'){const current=STATIONS.filter(s=>s.km<=km+.05).at(-1)||STATIONS[0];const next=STATIONS.find(s=>s.km>km+.05)||STATIONS.at(-1);return{current,next};}const current=STATIONS.find(s=>s.km>=km-.05)||STATIONS.at(-1);const next=[...STATIONS].reverse().find(s=>s.km<km-.05)||STATIONS[0];return{current,next};}
  chooseLoop(t,b,used){const direction=t.direction;const entry=direction==='UP'?Number(b.location_from_km):Number(b.location_to_km);const candidates=LOOPS.filter(l=>!used.has(l.id)).map(l=>{const station=STATIONS.find(s=>s.id===l.station);return station?{l,station}:null;}).filter(Boolean).filter(({l,station})=>{const loopKm=station.km;if(direction==='UP' && !(loopKm>Number(t.current_km)&&loopKm<entry-.5))return false;if(direction==='DN' && !(loopKm<Number(t.current_km)&&loopKm>entry+.5))return false;const exit=Number(l.exit_km);if(direction==='UP'&&exit<=Number(b.location_to_km))return false;if(direction==='DN'&&exit>=Number(b.location_from_km))return false;return true;});if(!candidates.length)return null;const {l,station}=candidates.sort((a,b)=>Math.abs(a.station.km-t.current_km)-Math.abs(b.station.km-t.current_km))[0];return{loop_id:l.id,station_id:station.id,station_code:station.code,entry_km:station.km,exit_km:l.exit_km,block_entry_km:entry,distance_km:Math.abs(station.km-t.current_km),capacity:l.capacity,map_y_up:l.map_y_up,map_y_dn:l.map_y_dn};}
  evaluate(){const controls={},conflicts=[],advisories=[],used=new Set();for(const track of ['UP_LINE','DN_LINE']){const list=this.trains.filter(t=>t.track===track&&!(t.route_control?.mode==='LOOP'&&t.route_control?.status==='ON_LOOP')).slice().sort((a,b)=>track==='UP_LINE'?a.current_km-b.current_km:b.current_km-a.current_km);for(let i=0;i<list.length-1;i++){const lead=list[i],trail=list[i+1],gap=Math.abs(lead.current_km-trail.current_km);if(gap<1.8){const action=gap<1?'HOLD':'SPEED_REGULATION';const item={advisory_id:`A-C-${lead.train_no}-${trail.train_no}`,train_no:trail.train_no,type:action,target_speed_kmh:action==='HOLD'?0:40,severity:action==='HOLD'?'CRITICAL':'WARNING',station:trail.next_station_code||'CTRL',headway_km:Number(gap.toFixed(2)),current_speed_kmh:Number((trail.effective_speed_kmh??trail.speed_kmh).toFixed(1)),leading_speed_kmh:Number((lead.effective_speed_kmh??lead.speed_kmh).toFixed(1)),reason:`${action.replace('_',' ')} ${trail.train_no} behind ${lead.train_no}.`};conflicts.push({conflict_id:item.advisory_id,track,leading_train:lead.train_no,trailing_train:trail.train_no,headway_km:item.headway_km,severity:item.severity,recommended_action:action});advisories.push(item);controls[trail.train_no]={action,target_speed_kmh:item.target_speed_kmh,source:'AI-3',reason:item.reason,conflict_id:item.advisory_id};}}}
    for(const t of this.trains){if(t.route_control?.mode==='LOOP'&&t.route_control?.status!=='REJOINED'){const via=t.route_control.via;controls[t.train_no]={action:'REROUTE_VIA_LOOP',target_speed_kmh:40,source:'AI-3',reason:`${t.train_no} is committed to ${via.loop_id} around ${t.route_control.protected_block_id}.`,block_id:t.route_control.protected_block_id,route_via:via};advisories.push({advisory_id:`A-ROUTE-${t.route_control.protected_block_id}-${t.train_no}`,train_no:t.train_no,type:'REROUTE_VIA_LOOP',target_speed_kmh:40,severity:'WARNING',block_id:t.route_control.protected_block_id,route_via:via,reason:`Reroute ${t.train_no} via ${via.loop_id}.`});continue;}
      const active=this.blocks.filter(b=>b.status==='Active'&&b.target_track===t.track);for(const b of active){const entry=t.direction==='UP'?Number(b.location_from_km):Number(b.location_to_km);const distance=t.direction==='UP'?entry-t.current_km:t.current_km-entry;if(distance<0)continue;if(distance<=1.5){controls[t.train_no]={action:'HOLD',target_speed_kmh:0,source:'AI-3',reason:`Hold ${t.train_no} before ${b.block_id}.`,block_id:b.block_id};advisories.push({advisory_id:`A-BLOCK-${b.block_id}-${t.train_no}`,train_no:t.train_no,type:'HOLD',target_speed_kmh:0,severity:'CRITICAL',block_id:b.block_id,distance_to_block_km:Number(distance.toFixed(2)),reason:`Protect active possession ${b.block_id}.`});}
        else if(distance<=4){const cur=controls[t.train_no];if(!cur||cur.action!=='HOLD')controls[t.train_no]={action:'SPEED_REGULATION',target_speed_kmh:30,source:'AI-3',reason:`Regulate ${t.train_no} before ${b.block_id}.`,block_id:b.block_id};}
        else if(distance<=8){const loop=this.chooseLoop(t,b,used);if(loop){used.add(loop.loop_id);controls[t.train_no]={action:'REROUTE_VIA_LOOP',target_speed_kmh:40,source:'AI-3',reason:`Route ${t.train_no} via ${loop.loop_id} before ${b.block_id}.`,block_id:b.block_id,route_via:loop};advisories.push({advisory_id:`A-BLOCK-${b.block_id}-${t.train_no}`,train_no:t.train_no,type:'REROUTE_VIA_LOOP',target_speed_kmh:40,severity:'WARNING',block_id:b.block_id,distance_to_block_km:Number(distance.toFixed(2)),route_via:loop,reason:`Route ${t.train_no} via ${loop.loop_id} before ${b.block_id}.`});}}
      }}
    this.ai3State={engine:'AI-3 MANAGE',status:'LIVE',controls,conflicts,advisories,signals:STATIONS.map(s=>({station_id:s.id,aspects:{UP_LINE:this.blocks.some(b=>b.status==='Active'&&b.target_track==='UP_LINE'&&s.km>=b.location_from_km-.2&&s.km<=b.location_to_km+.2)?'RED':'GREEN',DN_LINE:this.blocks.some(b=>b.status==='Active'&&b.target_track==='DN_LINE'&&s.km>=b.location_from_km-.2&&s.km<=b.location_to_km+.2)?'RED':'GREEN'}})),active_conflicts_count:conflicts.length,active_advisories_count:advisories.length,evaluated_train_count:this.trains.length,control_count:Object.keys(controls).length,controller_mode:'CLOSED_LOOP_SIMULATION'};return this.ai3State;}
  tick(){this.sequence++;this.evaluate();const controls=this.ai3State.controls;for(const t of this.trains){let c=controls[t.train_no]||{action:'NORMAL',target_speed_kmh:t.speed_kmh};let target=Number(c.target_speed_kmh??t.speed_kmh);const rc=t.route_control;
      if(c.action==='REROUTE_VIA_LOOP'&&c.route_via&&!rc){t.route_control={mode:'LOOP',status:'DIVERSION_PENDING',via:c.route_via,protected_block_id:c.block_id,loop_progress_km:0};}
      const r=t.route_control;
      if(r?.mode==='LOOP'&&r.via){const entry=Number(r.via.entry_km),exit=Number(r.via.exit_km);if(r.status==='DIVERSION_PENDING'){const step=target/3600*8;const proposed=t.current_km+(t.direction==='UP'?step:-step);const reached=t.direction==='UP'?proposed>=entry:proposed<=entry;if(reached){t.current_km=entry;r.status='ON_LOOP';r.loop_progress_km=0;}else{t.current_km=proposed;}}
        if(r.status==='ON_LOOP'){const step=target/3600*8;const total=Math.abs(exit-entry);r.loop_progress_km=Number(r.loop_progress_km||0)+step;if(r.loop_progress_km>=total){t.current_km=exit;r.status='REJOINED';t.status='AI-3 REJOINED MAIN LINE';}else{t.current_km=entry+(t.direction==='UP'?1:-1)*r.loop_progress_km;t.status='AI-3 ON LOOP';}t.effective_speed_kmh=target;t.actual_speed_kmh=target;t.commanded_speed_kmh=target;t.control_action='REROUTE_VIA_LOOP';}
        if(r.status==='REJOINED'){t.route_control={mode:'MAIN',status:'REJOINED',via:r.via};t.status='AI-3 REJOINED MAIN LINE';}
      } else {const active=this.blocks.find(b=>b.status==='Active'&&b.target_track===t.track&&((t.direction==='UP'&&t.current_km<b.location_from_km&&t.current_km+target/3600*8>=b.location_from_km)||(t.direction==='DN'&&t.current_km>b.location_to_km&&t.current_km-target/3600*8<=b.location_to_km)));if(c.action==='HOLD'||active){t.effective_speed_kmh=0;t.actual_speed_kmh=0;t.commanded_speed_kmh=0;t.control_action='HOLD';t.status='HOLD AT SIGNAL';}else{const step=target/3600*8;t.current_km+=t.direction==='UP'?step:-step;if(t.current_km>25)t.current_km=0;if(t.current_km<0)t.current_km=25;t.effective_speed_kmh=target;t.actual_speed_kmh=target;t.commanded_speed_kmh=target;t.control_action=c.action;t.status=c.action==='NORMAL'?'ON TIME':'AI-3 CONTROLLED';}}
      const ctx=this.stationContext(t);t.current_station=ctx.current.name;t.current_station_code=ctx.current.code;t.next_station=ctx.next.name;t.next_station_code=ctx.next.code;t.block_context=(t.route_control?.mode==='LOOP')?null:null;t.route_control=t.route_control||null;t.effective_speed_kmh=Number(t.effective_speed_kmh??t.speed_kmh);t.actual_speed_kmh=Number(t.actual_speed_kmh??t.effective_speed_kmh);t.commanded_speed_kmh=Number(t.commanded_speed_kmh??t.actual_speed_kmh);
    }
    this.evaluate();this.emit();}
  plan(){const actions=this.trains.map(t=>({train_no:t.train_no,train_name:t.name,source:t.origin,destination:t.destination,direction:t.direction,current_km:Number(t.current_km.toFixed(2)),current_speed_kmh:Number((t.actual_speed_kmh??t.effective_speed_kmh??t.speed_kmh??0).toFixed(1)),route_status:t.route_control?.status||'MAIN_LINE',loop_id:t.route_control?.via?.loop_id||null,action:(this.ai3State.controls[t.train_no]?.action)||'NORMAL',delay_minutes:0,reason:this.ai3State.controls[t.train_no]?.reason||'Generated from current simulated corridor state.'}));this.ai1={engine:'AI-1 PLAN',solver:'PRESENTATION-SAFE HEURISTIC',actions,summary:{affected_trains:actions.filter(a=>a.action!=='NORMAL').length,total_planned_delay_minutes:0,active_blocks_considered:this.blocks.filter(b=>b.status==='Active').length,maintenance_tasks_considered:this.blocks.length}};this.events.unshift({type:'AI1_PLAN_GENERATED',at:new Date().toISOString()});this.emit();return this.ai1;}
  emergency(locationKm,duration=45,track='UP_LINE'){const km=Math.max(0,Math.min(25,Number(locationKm)||12)),end=Math.min(25,km+1.2),block={block_id:`EMG-DEMO-${++this.sequence}`,section:`KM ${km.toFixed(1)} - ${end.toFixed(1)}`,location_from_km:km,location_to_km:end,target_track:track,status:'Active',approved:true,emergency:true,duration_minutes:Number(duration),disruption_type:'Emergency Maintenance'};this.blocks.unshift(block);this.events.unshift({type:'AI2_EMERGENCY',block_id:block.block_id});this.emit();return{engine:'AI-2 ADAPT',status:'ACTIVATED',emergency_block:block};}
  snapshot(){return{type:'telemetry',sequence:this.sequence,server_time:new Date().toISOString(),corridor:{id:'CORR_SDAH_BP',name:'Sealdah - Barrackpore Custom OCC Corridor',length_km:25,stations:STATIONS,tracks:['UP_LINE','DN_LINE']},trains:structuredClone(this.trains),active_blocks:this.blocks.filter(b=>b.status==='Active'),planned_blocks:this.blocks.filter(b=>b.status==='Planned'),ai1:this.ai1,ai3:this.ai3State,events:this.events.slice(0,20)};}
  emit(){const snap=this.snapshot();this.onSnapshot(snap);window.dispatchEvent(new CustomEvent('rail-telemetry',{detail:snap}));}
}
